In [4]:
import json
import pandas as pd

WEATHER_FILE = "../data/raw/weather_6158731_2025.json"

with open(WEATHER_FILE, "r", encoding="utf-8") as file:
    data = json.load(file)

weather = pd.DataFrame(
    feature["properties"]
    for feature in data["features"]
)

weather.head()

,STATION_NAME,CLIMATE_IDENTIFIER,ID,LOCAL_DATE,PROVINCE_CODE,LOCAL_YEAR,LOCAL_MONTH,LOCAL_DAY,LOCAL_HOUR,UTC_DATE,...,WINDCHILL,WINDCHILL_FLAG,WIND_DIRECTION,WIND_DIRECTION_FLAG,WIND_SPEED,WIND_SPEED_FLAG,STN_ID,LONGITUDE_DECIMAL_DEGREES,LATITUDE_DECIMAL_DEGREES,FLAG
0,TORONTO INTL A,6158731,6158731.2025.1.1.3,2025-01-01 03:00:00,ON,2025,1,1,3,2025-01-01T08:00:00,...,NaN,None,34.0,None,26.0,None,51459,-79.630556,43.676667,None
1,TORONTO INTL A,6158731,6158731.2025.1.1.0,2025-01-01 00:00:00,ON,2025,1,1,0,2025-01-01T05:00:00,...,NaN,None,35.0,None,27.0,None,51459,-79.630556,43.676667,None
2,TORONTO INTL A,6158731,6158731.2025.1.1.1,2025-01-01 01:00:00,ON,2025,1,1,1,2025-01-01T06:00:00,...,NaN,None,35.0,None,29.0,None,51459,-79.630556,43.676667,None
3,TORONTO INTL A,6158731,6158731.2025.1.1.2,2025-01-01 02:00:00,ON,2025,1,1,2,2025-01-01T07:00:00,...,NaN,None,35.0,None,30.0,None,51459,-79.630556,43.676667,None
4,TORONTO INTL A,6158731,6158731.2025.1.1.4,2025-01-01 04:00:00,ON,2025,1,1,4,2025-01-01T09:00:00,...,NaN,None,34.0,None,23.0,None,51459,-79.630556,43.676667,None

In [5]:
weather.shape

(8760, 39)

In [6]:
weather.columns.tolist()

['STATION_NAME',
 'CLIMATE_IDENTIFIER',
 'ID',
 'LOCAL_DATE',
 'PROVINCE_CODE',
 'LOCAL_YEAR',
 'LOCAL_MONTH',
 'LOCAL_DAY',
 'LOCAL_HOUR',
 'UTC_DATE',
 'UTC_YEAR',
 'UTC_MONTH',
 'UTC_DAY',
 'TEMP',
 'TEMP_FLAG',
 'DEW_POINT_TEMP',
 'DEW_POINT_TEMP_FLAG',
 'HUMIDEX',
 'HUMIDEX_FLAG',
 'PRECIP_AMOUNT',
 'PRECIP_AMOUNT_FLAG',
 'RELATIVE_HUMIDITY',
 'RELATIVE_HUMIDITY_FLAG',
 'STATION_PRESSURE',
 'STATION_PRESSURE_FLAG',
 'VISIBILITY',
 'VISIBILITY_FLAG',
 'WEATHER_ENG_DESC',
 'WEATHER_FRE_DESC',
 'WINDCHILL',
 'WINDCHILL_FLAG',
 'WIND_DIRECTION',
 'WIND_DIRECTION_FLAG',
 'WIND_SPEED',
 'WIND_SPEED_FLAG',
 'STN_ID',
 'LONGITUDE_DECIMAL_DEGREES',
 'LATITUDE_DECIMAL_DEGREES',
 'FLAG']

In [7]:
weather[["LOCAL_DATE", "LOCAL_HOUR", "TEMP"]].head()

            LOCAL_DATE  LOCAL_HOUR  TEMP
0  2025-01-01 03:00:00           3   0.8
1  2025-01-01 00:00:00           0   1.6
2  2025-01-01 01:00:00           1   1.6
3  2025-01-01 02:00:00           2   1.4
4  2025-01-01 04:00:00           4   1.4

In [8]:
weather["TEMP"].isna().sum()

np.int64(1)